workflows:
  android-debug-test:
    name: HERMES Translator Build
    instance_type: mac_mini_m1

    environment:
      vars:
        PACKAGE_NAME: "com.hermes.translator"
        BUILD_NUMBER: 1
        VERSION_NAME: "1.0.0-alpha"

    scripts:
      - name: Setup Project
        script: |
          echo "⚡ HERMES TRANSLATOR BUILD STARTED"
          echo "Package: $PACKAGE_NAME"
          echo "Version: $VERSION_NAME ($BUILD_NUMBER)"

      - name: Fix Fonts
        script: |
          echo "🛡️ Fixing fonts..."
          mkdir -p app/src/main/res/font/
          cd app/src/main/res/font/

          echo "📄 Creating font-family XML files..."

          # --------------------
          # Cinzel font family
          # --------------------
          cat <<EOF > cinzel.xml
          <?xml version="1.0" encoding="utf-8"?>
          <font-family xmlns:android="http://schemas.android.com/apk/res/android"
              xmlns:app="http://schemas.android.com/apk/res-auto">
              <font android:fontStyle="normal" android:fontWeight="400"
                    android:font="@font/cinzel_regular"
                    app:font="@font/cinzel_regular"/>
              <font android:fontStyle="normal" android:fontWeight="700"
                    android:font="@font/cinzel_bold"
                    app:font="@font/cinzel_bold"/>
          </font-family>
          EOF

          # --------------------
          # Orbitron font family
          # --------------------
          cat <<EOF > orbitron.xml
          <?xml version="1.0" encoding="utf-8"?>
          <font-family xmlns:android="http://schemas.android.com/apk/res/android"
              xmlns:app="http://schemas.android.com/apk/res-auto">
              <font android:fontStyle="normal" android:fontWeight="400"
                    android:font="@font/orbitron_regular"
                    app:font="@font/orbitron_regular"/>
              <font android:fontStyle="normal" android:fontWeight="700"
                    android:font="@font/orbitron_bold"
                    app:font="@font/orbitron_bold"/>
          </font-family>
          EOF

          # --------------------
          # Rajdhani font family
          # --------------------
          cat <<EOF > rajdhani.xml
          <?xml version="1.0" encoding="utf-8"?>
          <font-family xmlns:android="http://schemas.android.com/apk/res/android"
              xmlns:app="http://schemas.android.com/apk/res-auto">
              <font android:fontStyle="normal" android:fontWeight="300"
                    android:font="@font/rajdhani_light"
                    app:font="@font/rajdhani_light"/>
              <font android:fontStyle="normal" android:fontWeight="400"
                    android:font="@font/rajdhani_regular"
                    app:font="@font/rajdhani_regular"/>
              <font android:fontStyle="normal" android:fontWeight="500"
                    android:font="@font/rajdhani_medium"
                    app:font="@font/rajdhani_medium"/>
          </font-family>
          EOF

          echo "⬇️ Downloading font files..."

          # Cinzel
          curl -s -L -o cinzel_regular.ttf "https://raw.githubusercontent.com/georgiau/cinzel/main/fonts/ttf/Cinzel-Regular.ttf"
          curl -s -L -o cinzel_bold.ttf "https://raw.githubusercontent.com/georgiau/cinzel/main/fonts/ttf/Cinzel-Bold.ttf"

          # Orbitron — FIXED (разделено в отдельные строки)
          curl -s -L -o orbitron_regular.ttf "https://raw.githubusercontent.com/theleagueof/orbitron/master/fonts/ttf/Orbitron-Regular.ttf"
          curl -s -L -o orbitron_bold.ttf "https://raw.githubusercontent.com/theleagueof/orbitron/master/fonts/ttf/Orbitron-Bold.ttf"

          # Rajdhani
          curl -s -L -o rajdhani_light.ttf "https://raw.githubusercontent.com/IndianTypeFoundry/Rajdhani/master/fonts/ttf/Rajdhani-Light.ttf"
          curl -s -L -o rajdhani_regular.ttf "https://raw.githubusercontent.com/IndianTypeFoundry/Rajdhani/master/fonts/ttf/Rajdhani-Regular.ttf"
          curl -s -L -o rajdhani_medium.ttf "https://raw.githubusercontent.com/IndianTypeFoundry/Rajdhani/master/fonts/ttf/Rajdhani-Medium.ttf"

          echo "📦 Checking downloaded fonts:"
          ls -la

          echo "✅ Fonts ready"

      - name: Build APK
        script: |
          echo "🔨 Building HERMES APK..."
          chmod +x ./gradlew
          ./gradlew clean assembleDebug \
            -PversionCode=$BUILD_NUMBER \
            -PversionName=$VERSION_NAME \
            --stacktrace --no-daemon

      - name: Check Result
        script: |
          APK_PATH=$(find . -name "*.apk" -path "*/debug/*" | head -1)
          if [ -f "$APK_PATH" ]; then
            echo "🎉 HERMES TRANSLATOR SUCCESSFULLY BUILT!"
            echo "APK: $(basename "$APK_PATH")"
            echo "Size: $(du -h "$APK_PATH" | cut -f1)"
          else
            echo "❌ Build failed"
            exit 1
          fi

    artifacts:
      - app/build/outputs/**/*.apk
