workflows:
  android-debug-test:
    name: Android Debug Build (Test)
    environment:
      groups: []
      vars:
        PACKAGE_NAME: "com.hermes.translator"
        BUILD_NUMBER: 1
        VERSION_NAME: "1.0.0-alpha"

    scripts:
      # 1. Переходим в директорию проекта
      - name: Go to build dir
        script: |
          cd $CM_BUILD_DIR
          echo "📁 Current directory: $(pwd)"

      # 2. Делаем Gradle Wrapper исполняемым
      - name: Prepare Gradle Wrapper
        script: |
          chmod +x ./gradlew
          ./gradlew --version

      # 3. Собираем APK через gradlew
      - name: Build APK
        script: |
          ./gradlew assembleDebug \
            -PversionCode=$BUILD_NUMBER \
            -PversionName=$VERSION_NAME \
            --stacktrace

      # 4. Проверка APK
      - name: Check APK
        script: |
          APK_PATH=$(find . -name "*.apk" -path "*/debug/*" | head -1)
          if [ -f "$APK_PATH" ]; then
            echo "🎉 SUCCESS! Hermes Translator APK built!"
            echo "📦 File: $APK_PATH"
            echo "📏 Size: $(du -h "$APK_PATH" | cut -f1)"
            echo ""
            echo "✨ HERMES TRANSLATOR FEATURES:"
            echo "   • System Audio Capture (Android 10+)"
            echo "   • Vosk Offline Speech Recognition"
            echo "   • Google ML Kit Translation"
            echo "   • Real-time Game Overlay"
            echo "   • PS Remote Play Detection"
            echo "   • 4 Translation Modes"
            echo "   • 3 Voice Types"
          else
            echo "❌ No APK found"
            find . -name "*.apk" -type f
            exit 1
          fi

    artifacts:
      - app/build/outputs/apk/debug/*.apk
