- name: Ensure Fonts Exist
  script: |
    echo "🛡️ Creating fonts..."
    mkdir -p app/src/main/res/font/
    cd app/src/main/res/font/
    
    # Простые XML (одной строкой)
    echo '<?xml version="1.0" encoding="utf-8"?><font-family xmlns:android="http://schemas.android.com/apk/res/android"><font android:font="@font/cinzel_regular" android:fontWeight="400"/><font android:font="@font/cinzel_bold" android:fontWeight="700"/></font-family>' > cinzel.xml
    echo '<?xml version="1.0" encoding="utf-8"?><font-family xmlns:android="http://schemas.android.com/apk/res/android"><font android:font="@font/orbitron_regular" android:fontWeight="400"/><font android:font="@font/orbitron_bold" android:fontWeight="700"/></font-family>' > orbitron.xml
    echo '<?xml version="1.0" encoding="utf-8"?><font-family xmlns:android="http://schemas.android.com/apk/res/android"><font android:font="@font/rajdhani_light" android:fontWeight="300"/><font android:font="@font/rajdhani_regular" android:fontWeight="400"/><font android:font="@font/rajdhani_medium" android:fontWeight="500"/></font-family>' > rajdhani.xml
    
    # Скачать шрифты...
