workflows:
  android-debug-test:
    name: HERMES Translator Build
    environment:
      groups: []
      vars:
        PACKAGE_NAME: "com.hermes.translator"
        BUILD_NUMBER: 1
        VERSION_NAME: "1.0.0-alpha"
        
    scripts:
      # 1. ОБЯЗАТЕЛЬНО: Создать шрифты
      - name: Ensure Fonts Exist
        script: |
          echo "🛡️ Ensuring HERMES fonts are present..."
          mkdir -p app/src/main/res/font/
          cd app/src/main/res/font/
          
          # Создать минимальные XML
          echo '<?xml version="1.0" encoding="utf-8"?>
          <font-family xmlns:android="http://schemas.android.com/apk/res/android">
            <font android:font="@font/cinzel_regular" android:fontWeight="400"/>
            <font android:font="@font/cinzel_bold" android:fontWeight="700"/>
          </font-family>' > cinzel.xml
          
          # Скачать основные шрифты
          curl -s -L -o cinzel_regular.ttf "https://raw.githubusercontent.com/georgiau/cinzel/main/fonts/ttf/Cinzel-Regular.ttf"
          curl -s -L -o cinzel_bold.ttf "https://raw.githubusercontent.com/georgiau/cinzel/main/fonts/ttf/Cinzel-Bold.ttf"
          
          echo "✅ HERMES fonts ready"

      # 2. Сборка (оригинальный ваш код)
      - name: Build HERMES APK
        script: |
          echo "🔨 Building HERMES with ALL features..."
          ./gradlew assembleDebug \
            -PversionCode=$BUILD_NUMBER \
            -PversionName=$VERSION_NAME \
            --stacktrace

      # 3. Проверка
      - name: Verify Build
        script: |
          if [ -f "app/build/outputs/apk/debug/*.apk" ]; then
            echo "🎉 HERMES SUCCESS! All features:"
            echo "   • Audio Capture ✓"
            echo "   • Game Overlay ✓"
            echo "   • Vosk Offline ✓"
            echo "   • ML Kit Translate ✓"
            echo "   • PS Remote Play ✓"
          else
            echo "❌ Build failed"
            exit 1
          fi
    
    artifacts:
      - app/build/outputs/apk/debug/*.apk
