workflows:
  android-debug-test:
    name: Android Debug Build (Test)
    environment:
      groups: []
      vars:
        PACKAGE_NAME: "com.hermes.translator"
        BUILD_NUMBER: 1
        VERSION_NAME: "1.0.0-alpha"
        
    scripts:
      # 1. СКАЧИВАЕМ И УСТАНАВЛИВАЕМ GRADLE НАПРЯМУЮ
      - name: Install Gradle directly
        script: |
          echo "📦 Installing Gradle 8.0..."
          
          # Скачиваем Gradle
          wget -q https://services.gradle.org/distributions/gradle-8.0-bin.zip
          unzip -q gradle-8.0-bin.zip
          
          # Добавляем в PATH
          export PATH="$(pwd)/gradle-8.0/bin:$PATH"
          echo "PATH updated: $PATH"
          
          # Проверяем
          gradle --version
          echo "✅ Gradle installed"
      
      # 2. ИСПОЛЬЗУЕМ GRADLE НАПРЯМУЮ (без ./gradlew)
      - name: Build APK with direct gradle
        script: |
          echo "🔨 Building APK with gradle command..."
          
          # Используем gradle вместо ./gradlew
          gradle assembleDebug \
            -PversionCode=$BUILD_NUMBER \
            -PversionName=$VERSION_NAME \
            --stacktrace \
            --no-daemon
      
      # 3. Проверка APK
      - name: Check APK
        script: |
          APK_PATH=$(find . -name "*.apk" -path "*/debug/*" | head -1)
          if [ -f "$APK_PATH" ]; then
            echo "🎉 SUCCESS! Hermes Translator APK built!"
            echo "📦 File: $APK_PATH"
            echo "📏 Size: $(du -h "$APK_PATH" | cut -f1)"
            
            # Информация о фичах
            echo ""
            echo "✨ HERMES TRANSLATOR FEATURES:"
            echo "   • System Audio Capture (Android 10+)"
            echo "   • Vosk Offline Speech Recognition"
            echo "   • Google ML Kit Translation"
            echo "   • Real-time Game Overlay"
            echo "   • PS Remote Play Detection"
            echo "   • 4 Translation Modes"
            echo "   • 3 Voice Types"
          else
            echo "❌ No APK found"
            find . -name "*.apk" -type f
            exit 1
          fi
    
    artifacts:
      - app/build/outputs/apk/debug/*.apk
    
    publishing:
      email:
        recipients:
          - ovanes931@gmail.com
        notify:
          success: true
          failure: true
