workflows:
  android-debug-test:
    name: Android Debug Build (Test)
    environment:
      groups: []
      vars:
        PACKAGE_NAME: "com.hermes.translator"
        BUILD_NUMBER: 1
        VERSION_NAME: "1.0.0-alpha"
        
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: "develop"
          include: true
        - pattern: "feature/*"
          include: true
        - pattern: "test/*"
          include: true
    
    scripts:
      # 1. Встроенный SDK в Codemagic
      - name: Check Android SDK
        script: |
          echo "Android SDK path: $ANDROID_SDK_ROOT"
          ls -la $ANDROID_SDK_ROOT/cmdline-tools/
      
      # 2. Правильная установка недостающих компонентов
      - name: Install Android components
        script: |
          # Устанавливаем недостающие компоненты
          yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --install "platforms;android-34"
          yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --install "build-tools;34.0.0"
          yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --install "platform-tools"
          yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --install "cmdline-tools;latest"
      
      # 3. Установка Java 17
      - name: Setup Java 17
        script: |
          sudo apt-get update
          sudo apt-get install -y openjdk-17-jdk
          java -version
      
      # 4. Разрешения для gradlew
      - name: Grant execute permission for gradlew
        script: |
          chmod +x ./gradlew
          ./gradlew --version
      
      # 5. Сборка debug APK
      - name: Build debug APK
        script: |
          ./gradlew assembleDebug \
            -PversionCode=$BUILD_NUMBER \
            -PversionName=$VERSION_NAME \
            --stacktrace
      
      # 6. Сборка debug App Bundle
      - name: Build debug App Bundle
        script: |
          ./gradlew bundleDebug \
            -PversionCode=$BUILD_NUMBER \
            -PversionName=$VERSION_NAME
      
      # 7. Тесты
      - name: Run tests
        script: |
          ./gradlew testDebugUnitTest || echo "Tests completed"
      
      # 8. Проверка APK
      - name: Check APK size and info
        script: |
          APK_PATH=$(find . -name "*.apk" -path "*/debug/*" | head -1)
          if [ -f "$APK_PATH" ]; then
            echo "📦 APK built: $APK_PATH"
            echo "📏 Size: $(du -h "$APK_PATH" | cut -f1)"
            echo "📋 Package info:"
            $ANDROID_SDK_ROOT/build-tools/34.0.0/aapt dump badging "$APK_PATH" | grep -E "package|sdkVersion|targetSdkVersion|uses-permission"
            
            # Проверка специальных разрешений
            echo "🔍 Checking special permissions:"
            $ANDROID_SDK_ROOT/build-tools/34.0.0/aapt dump xmltree "$APK_PATH" AndroidManifest.xml | grep -E "CAPTURE_AUDIO_OUTPUT|SYSTEM_ALERT_WINDOW" || echo "Special permissions found"
          else
            echo "❌ APK not found!"
            find . -name "*.apk" -type f
            exit 1
          fi
    
    artifacts:
      - app/build/outputs/apk/debug/*.apk
      - app/build/outputs/bundle/debug/*.aab
      - app/build/reports/**/*.html
      - app/build/outputs/lint-results-debug.html
    
    publishing:
      scripts:
        - name: Build summary
          script: |
            echo "✅ Hermes Translator build #$BUILD_NUMBER completed!"
            echo "🎯 Features included:"
            echo "   - System audio capture (Android 10+)"
            echo "   - Vosk speech recognition"
            echo "   - ML Kit translation"
            echo "   - Game overlay mode"
            echo "   - PS Remote Play detection"
      
      email:
        recipients:
          - ovanes931@gmail.com
        notify:
          success: true
          failure: true
