workflows:
  android-debug-test:
    name: Android Debug Build (Test)
    environment:
      groups: []
      vars:
        PACKAGE_NAME: "com.hermes.translator"
        BUILD_NUMBER: 1
        VERSION_NAME: "1.0.0-alpha"
        
    scripts:
      # 1. ФИКС СРАЗУ ВСЕГО
      - name: Fix everything at once
        script: |
          echo "🔧 ONE-TIME FIX FOR CODEMAGIC..."
          
          # Удаляем Windows файл
          rm -f gradlew.bat
          
          # Исправляем кавычки в gradlew
          sed -i '' "s/DEFAULT_JVM_OPTS='\"-Xmx64m\" \"-Xms64m\"'/DEFAULT_JVM_OPTS='-Xmx1024m -Xms256m'/g" gradlew
          
          # Даём права
          chmod +x ./gradlew
          
          # СКАЧИВАЕМ GRADLE ВРУЧНУЮ
          echo "📦 Downloading Gradle 8.0..."
          wget -q https://services.gradle.org/distributions/gradle-8.0-bin.zip
          unzip -q gradle-8.0-bin.zip
          mkdir -p ~/.gradle/wrapper/dists/gradle-8.0-bin/
          cp -r gradle-8.0/* ~/.gradle/wrapper/dists/gradle-8.0-bin/
          
          # ТЕСТ
          echo "🚀 Testing..."
          ./gradlew --version || {
            echo "❌ Still failing, using system gradle..."
            # Используем системный gradle как запасной вариант
            gradle --version 2>/dev/null || echo "No system gradle"
          }
      
      # 2. Сборка APK
      - name: Build APK
        script: |
          echo "🔨 Building APK..."
          ./gradlew assembleDebug \
            -PversionCode=$BUILD_NUMBER \
            -PversionName=$VERSION_NAME \
            --stacktrace \
            --no-daemon
      
      # 3. Проверка
      - name: Check APK
        script: |
          APK_PATH=$(find . -name "*.apk" -path "*/debug/*" | head -1)
          if [ -f "$APK_PATH" ]; then
            echo "✅ SUCCESS! APK: $APK_PATH"
            echo "📏 Size: $(du -h "$APK_PATH" | cut -f1)"
          else
            echo "❌ No APK found"
          fi
    
    artifacts:
      - app/build/outputs/apk/debug/*.apk
    
    publishing:
      email:
        recipients:
          - ovanes931@gmail.com
        notify:
          success: true
          failure: true
