workflows:
  android-debug-test:
    name: Hermes Translator - Debug Build
    environment:
      groups: []
      vars:
        PACKAGE_NAME: "com.hermes.translator"
        BUILD_NUMBER: 1
        VERSION_NAME: "1.0.0-alpha"
        
    scripts:
      # 0. Проверка структуры HERMES
      - name: HERMES Structure Check
        script: |
          echo "⚡ HERMES TRANSLATOR BUILD STARTED ⚡"
          echo "========================================"
          echo "🎯 Target: Android Game Audio Translator"
          echo "📱 Package: $PACKAGE_NAME"
          echo "🔢 Version: $VERSION_NAME ($BUILD_NUMBER)"
          echo ""
          echo "📁 Project Structure:"
          echo "   ✓ Audio Capture Module"
          echo "   ✓ Game Overlay Service"
          echo "   ✓ Vosk Recognition"
          echo "   ✓ Translation Engine"
          echo "   ✓ UI/UX Components"
          echo "   ✓ Fonts (Cinzel, Orbitron, Rajdhani)"
          echo "========================================"

      # 1. Настройка шрифтов (если их нет в Git)
      - name: Setup HERMES Fonts
        script: |
          echo "🔤 Setting up HERMES UI fonts..."
          mkdir -p app/src/main/res/font/
          
          # Если файлов нет — скачиваем минимальный набор
          if [ ! -f "app/src/main/res/font/cinzel_regular.ttf" ]; then
            echo "⬇️  Downloading Cinzel (for headers)..."
            curl -s -L -o app/src/main/res/font/cinzel_regular.ttf \
              "https://github.com/georgiau/cinzel/raw/main/fonts/ttf/Cinzel-Regular.ttf"
          fi
          
          if [ ! -f "app/src/main/res/font/orbitron_regular.ttf" ]; then
            echo "⬇️  Downloading Orbitron (for overlay)..."
            curl -s -L -o app/src/main/res/font/orbitron_regular.ttf \
              "https://github.com/theleagueof/orbitron/raw/master/fonts/ttf/Orbitron-Regular.ttf"
          fi
          
          echo "✅ HERMES fonts ready"

      # 2. Gradle Wrapper (оригинальный)
      - name: Prepare Gradle Wrapper
        script: |
          chmod +x ./gradlew
          ./gradlew --version

      # 3. Сборка HERMES
      - name: Build HERMES APK
        script: |
          echo "🔨 Building HERMES Translator APK..."
          echo "========================================"
          echo "🔄 Features being compiled:"
          echo "   • System Audio Capture"
          echo "   • Real-time Game Overlay"
          echo "   • Offline Speech Recognition"
          echo "   • PS Remote Play Detection"
          echo "   • 4 Translation Modes"
          echo "========================================"
          
          ./gradlew assembleDebug \
            -PversionCode=$BUILD_NUMBER \
            -PversionName=$VERSION_NAME \
            --stacktrace \
            --no-daemon

      # 4. Проверка результата
      - name: Verify HERMES Build
        script: |
          APK_PATH=$(find . -name "*debug*.apk" | head -1)
          if [ -f "$APK_PATH" ]; then
            echo ""
            echo "🎉🎉🎉 HERMES TRANSLATOR SUCCESSFULLY BUILT! 🎉🎉🎉"
            echo "================================================"
            echo "📦 APK: $(basename $APK_PATH)"
            echo "📏 Size: $(du -h "$APK_PATH" | cut -f1)"
            echo "🔢 Version: $VERSION_NAME"
            echo ""
            echo "🚀 READY FOR DEPLOYMENT:"
            echo "   • Install on Android 10+ device"
            echo "   • Enable 'Display over other apps'"
            echo "   • Grant audio capture permission"
            echo "   • Start translation in games/PS Remote Play"
            echo "================================================"
          else
            echo "❌ HERMES build failed"
            exit 1
          fi
    
    artifacts:
      - app/build/outputs/apk/debug/*.apk
