workflows:
  android-debug-test:
    name: Android Debug Build (Test)
    environment:
      groups: []
      vars:
        PACKAGE_NAME: "com.hermes.translator"
        BUILD_NUMBER: 1
        VERSION_NAME: "1.0.0-alpha"
        
    scripts:
      # 1. Делаем wrapper исполняемым
      - name: Prepare Gradle Wrapper
        script: |
          chmod +x ./gradlew
          ./gradlew --version

      # 2. Собираем APK через Gradle Wrapper
      - name: Build APK
        script: |
          echo "🔨 Building APK with Gradle Wrapper..."
          ./gradlew assembleDebug \
            -PversionCode=$BUILD_NUMBER \
            -PversionName=$VERSION_NAME \
            --stacktrace \
            --no-daemon

      # 3. Проверяем, что APK собрался
      - name: Check APK
        script: |
          APK_PATH=$(find . -name "*.apk" -path "*/debug/*" | head -1)
          if [ -f "$APK_PATH" ]; then
            echo "🎉 SUCCESS! Hermes Translator APK built!"
            echo "📦 File: $APK_PATH"
            echo "📏 Size: $(du -h "$APK_PATH" | cut -f1)"
            
            # Информация о фичах
            echo ""
            echo "✨ HERMES TRANSLATOR FEATURES:"
            echo "   • System Audio Capture (Android 10+)"
            echo "   • Vosk Offline Speech Recognition"
            echo "   • Google ML Kit Translation"
            echo "   • Real-time Game Overlay"
            echo "   • PS Remote Play Detection"
            echo "   • 4 Translation Modes"
            echo "   • 3 Voice Types"
          else
            echo "❌ No APK found"
            find . -name "*.apk" -type f
            exit 1
          fi
    
    artifacts:
      - app/build/outputs/apk/debug/*.apk
